#!/usr/bin/env ruby

require File.expand_path('../../config/environment', __FILE__)
require File.expand_path('../../config/schedule', __FILE__)
require 'crom/command'

Crom::Command.new(ARGV).daemonize
