#!/usr/bin/env ruby

args = ARGV.dup
env = 'production'

if i = args.index('-e')
  env = args.delete_at(i + 1)
  args.delete('-e')
end

ENV['RAILS_ENV'] = env

require File.expand_path('../../config/environment', __FILE__)
require File.expand_path('../../config/schedule', __FILE__)
require 'crom/command'

Crom::Command.new(args).daemonize
